version: '3.4'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_DB: next_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8"
      TZ: "Asia/Tokyo"
    volumes:
      - ./db/initdb:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bash -c "rm -rf /next-api/tmp/pids/server.pid && bundle install && bundle exec rails db:create && bundle exec ridgepole -c config/database.yml -E development --apply -f db/Schemafile && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/next-api:cached
    ports:
      - "3000:3000"
    privileged: true
    depends_on:
      - db
    stdin_open: true

volumes:
  assets:
    driver: local